[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "livedocs"
version = "1.0.0"
description = "Python SDK for Livedocs"
authors = [{ name = "Livedocs" }]
dependencies = [
    "requests>=2.32,<3",
    "jinja2>=3.1,<4",
    "polars>=1.9,<2",
    "vegafusion[embed]>=1.6,<2",
    "pandas>=2.2,<3",
    "pyarrow>=17.0,<18",
    "db-dtypes>=1.3,<2",
    "duckdb>=1.2,<2",
    "altair>=5.4,<6",
    "pydantic>=2.9,<3",
    "msgpack>=1.1,<2",
    "sentry-sdk>=2.16,<3",
    "google-cloud-bigquery>=3.29.0,<4",
    "ipython==9.1.0",
    "tqdm>=4.67.1",
    "snowflake-connector-python>=3.15.0,<4",
    "cryptography>=44.0.1",
    "clickhouse-connect>=0.8.17",
    "psycopg[binary]>=3.2.12",
    "databricks-sql-connector>=4.1.4",
]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
homepage = "https://github.com/livedocs-io/vm-lib"

[tool.setuptools.packages.find]
where = ["."]
include = ["livedocs"]

[project.optional-dependencies]
test = ["flask", "flask-cors"]
